// Generated by CoffeeScript 1.8.0
var goodbye, hello;

hello = function() {
  return console.log("Hello World");
};

goodbye = function() {
  return console.log("Good bye");
};

hello();

goodbye();
